### ISSUE TITLE
Compare I/O and Metadata in xarray and CDAT

### ISSUE THREAD

**Issue by pochedls** [XCDAT/xcdat_test#11]
Compare read / write in xarray and CDAT, including:

* Ability to read file header and metadata (without loading full contents)
* What is the default (load data into memory? only load when an operation is performed?)
* Types of files each reads (do they both handle older file types, e.g., grib?)
* What is the process of labelling an array with axis information to save a netCDF file?

**Comment by tomvothecoder** [comment]
* Ability to read file header and metadata (without loading full contents)

* What is the default (load data into memory? only load when an operation is performed?)
  >Data is always loaded lazily from netCDF files. You can manipulate, slice and subset Dataset and DataArray objects, and no array values are loaded into memory until you try to perform some sort of actual computation.
  > &mdash; <cite>http://xarray.pydata.org/en/stable/io.html#netcdf</cite>

  > Lazy/on-demand data loading by open_dataset (and open_dataarray)
  >- `xr.open_dataset` loads only .coords into memory -> selection/slicing by index works!
  >- data variables loaded only on actual values access (calculation, slicing, ...) or with .load()
  >- `xr.load_dataset` follows `xr.open_dataset` by .load() -> loads all data into memory
  > &mdash; <cite>https://www.youtube.com/watch?v=ww4EYv20Ucw&t=786s</cite>

* Types of files each reads (do they both handle older file types, e.g., grib?)
  > File types: NetCDF 3/4, Iris, OPenDAP, Pickle, Dictionary, RasterIO, Zarr, GRIB1/2, PyNio, PsuedoNetCDF 
  > Interoperability: Pandas, Iris, CDMS, dask DataFrame
  > &mdash; <cite>http://xarray.pydata.org/en/stable/io.html#</cite>

* What is the process of labelling an array with axis information to save a netCDF file?
