### ISSUE TITLE
Add notebook to validate bounds functions

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat_test#22]
Validation Checklist
1. API usage (and plots where helpful)
2. Performance metrics (use timeit)
3. Bugs, improvements
4. Questions

Compare below APIs with CDAT equivalent.

* `ds.xcdat.fill_missing_bounds()` or `ds.bounds.fill_missing()`
* `ds.xcdat.get_bounds()` or `ds.bounds.get_bounds()`
* `ds.xcdat.add_bounds()` or `ds.bounds.add_bounds()`

**Comment by chengzhuzhang** [comment]
One minor point I would like to propose:
Can we consider add lower case `x` `y` `t`, in BoundsAxis = Literal["lat", "latitude", "Y", "lon", "longitude", "X", "time", "T"]
https://github.com/XCDAT/xcdat/blob/194f84de48a64ed9e072f183917989d4889ea7a5/xcdat/bounds.py#L15
I understand those may not be CF compliant, but supported by cdat and some other similar packages.

**Comment by lee1043** [comment]
I like @chengzhuzhang's idea! Some dataset (e.g., OBS) has not been on track of CF compliant and it is not uncommon that they used x, y, t for their dimensions. It would be nice if that can be recognized.

**Comment by tomvothecoder** [comment]
This should be done without needing a notebook (integration in PMP, users trying out xCDAT, etc.)
